-module(mylib_SUITE).

-compile([export_all,
          {parse_transform, pt_auto_properties}]).

-include_lib("common_test/include/ct.hrl").
-include_lib("proper/include/proper.hrl").

all() ->
    [test_manually_crafted_property,
     prop_same_but_autogenerated].

init_per_suite(Config) ->
    [{'start', 5}, {'end', 10}, {expected, ok} | Config].

test_mylib() ->
    [{userdata,[{doc,"Testing the mylib module"}]}].

test_mylib(_Config) ->
    {skip,"Not implemented."}.

manually_crafted_property(C) ->
    ?FORALL(X, integer(?config('start', C), ?config('end', C)),
            mylib:my_func(X) =:= ?config(expected, C)).

prop_same_but_autogenerated(C) ->
    ?FORALL(X, integer(?config('start', C), ?config('end', C)),
            mylib:my_func(X) =:= ?config(expected, C)).

test_manually_crafted_property(Config) ->
    true = proper:quickcheck(manually_crafted_property(Config), []).
