# run with ./cmain
cmain:
	gcc -o cmain main.o -L . -lmylib

# with Rust standard library
# run with LD_LIBRARY_PATH=/home/erszcz/apps/rust/0.10/lib ./cmain
#cmain:
#    gcc -o cmain main.o -L . -lmylib -L /home/erszcz/apps/rust/0.10/lib/ -lstd-8b97b62e-0.10
