[package]
name = "cbor-test"
version = "0.1.0"
authors = ["Radek Szymczyszyn <radoslaw.szymczyszyn@erlang-solutions.com>"]

[dependencies]
cbor = "0.3"
rustc-serialize = "0.3.24"

[[bin]]
doc  = false
name = "print"
path = "src/bin/print.rs"
