[package]
name = "cbor-test"
version = "0.1.0"
authors = ["Radek Szymczyszyn <radoslaw.szymczyszyn@erlang-solutions.com>"]

[dependencies]
serde = "1.0.0"
serde_cbor = "0.10.2"
serde_json = "1.0"

[[bin]]
doc  = false
name = "cbor"
path = "src/bin/cbor.rs"
