{application,ets_iter,
             [{description,[]},
              {vsn,"1"},
              {registered,[]},
              {applications,[kernel,stdlib]},
              {mod,{ets_iter_app,[]}},
              {env,[]},
              {modules,[ets_iter_app,ets_iter_sup,ets_iter_worker,mnesia_test,
                        test]}]}.
