apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  myvalue: "Hello World"
  drink: {{ .Values.favorite.drink }}
  food: {{ .Values.favorite.food }}
  {{- if .Values.hated }}
  hated:
    food: {{ .Values.hated.food }}
    drink: {{ .Values.hated.drink }}
  {{- end }}
